In [1]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("exploreation") \
    .master("local[*]") \
    .getOrCreate()
spark

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

26/09/02 14:23:37 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [4]:
df = spark.read.parquet("hdfs://uber-hadoop-master:9000/data/bronze/rides/*")

In [11]:
from pyspark.sql.functions import col

df2 = df

for column, dtype in df.dtypes:
    if dtype == "timestamp":
        df2 = df2.withColumn(column, col(column).cast("string"))

pdf = df2.limit(10).toPandas()

pdf

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag
0,HV0003,B03404,B03404,2024-01-01 00:21:47,2024-01-01 00:25:06,2024-01-01 00:28:08,2024-01-01 01:05:39,161,158,2.83,...,4.05,2.75,0.0,0.0,40.18,N,N,N,N,N
1,HV0003,B03404,B03404,2024-01-01 00:10:56,2024-01-01 00:11:08,2024-01-01 00:12:53,2024-01-01 00:20:05,137,79,1.57,...,0.89,2.75,0.0,0.0,6.12,N,N,N,N,N
2,HV0003,B03404,B03404,2024-01-01 00:20:04,2024-01-01 00:21:51,2024-01-01 00:23:05,2024-01-01 00:35:16,79,186,1.98,...,1.60,2.75,0.0,0.0,9.47,N,N,N,N,N
3,HV0003,B03404,B03404,2024-01-01 00:35:46,2024-01-01 00:39:59,2024-01-01 00:41:04,2024-01-01 00:56:34,234,148,1.99,...,1.52,2.75,0.0,0.0,11.35,N,N,N,N,N
4,HV0003,B03404,B03404,2024-01-01 00:48:19,2024-01-01 00:56:23,2024-01-01 00:57:21,2024-01-01 01:10:02,148,97,2.65,...,3.43,2.75,0.0,0.0,28.63,N,N,N,N,N
5,HV0003,B03404,B03404,2024-01-01 00:03:47,2024-01-01 00:05:53,2024-01-01 00:06:15,2024-01-01 00:27:53,255,95,7.02,...,2.85,0.00,0.0,0.0,24.35,N,N,N,N,Y
6,HV0003,B03404,B03404,2024-01-01 00:22:51,2024-01-01 00:29:17,2024-01-01 00:29:47,2024-01-01 00:50:08,95,212,11.33,...,4.68,0.00,0.0,0.0,30.98,N,N,N,N,Y
7,HV0003,B03404,B03404,2024-01-01 00:45:34,2024-01-01 00:57:29,2024-01-01 00:57:50,2024-01-01 01:11:27,213,47,3.43,...,2.06,0.00,0.0,0.0,20.73,N,N,N,N,Y
8,HV0003,B03404,B03404,2024-01-01 00:11:51,2024-01-01 00:15:46,2024-01-01 00:16:00,2024-01-01 00:28:13,209,114,1.54,...,1.37,2.75,0.0,0.0,10.40,N,N,N,N,Y
9,HV0003,B03404,B03404,2024-01-01 00:26:48,2024-01-01 00:33:02,2024-01-01 00:33:15,2024-01-01 00:46:39,113,209,1.72,...,1.21,2.75,0.0,0.0,11.38,N,N,N,N,Y

In [5]:
df.count()

198414064

In [2]:
df = spark.read.parquet(
    "hdfs://uber-hadoop-master:9000/data/bronze/rides/fhvhv_tripdata_2024-01.parquet"
)

df.printSchema()

root
 |-- hvfhs_license_num: string (nullable = true)
 |-- dispatching_base_num: string (nullable = true)
 |-- originating_base_num: string (nullable = true)
 |-- request_datetime: timestamp (nullable = true)
 |-- on_scene_datetime: timestamp (nullable = true)
 |-- pickup_datetime: timestamp (nullable = true)
 |-- dropoff_datetime: timestamp (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- trip_miles: double (nullable = true)
 |-- trip_time: long (nullable = true)
 |-- base_passenger_fare: double (nullable = true)
 |-- tolls: double (nullable = true)
 |-- bcf: double (nullable = true)
 |-- sales_tax: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- airport_fee: double (nullable = true)
 |-- tips: double (nullable = true)
 |-- driver_pay: double (nullable = true)
 |-- shared_request_flag: string (nullable = true)
 |-- shared_match_flag: string (nullable = true)
 |-- access_a_ride_flag: string (nullable = true)
 |-- wav_request_flag: string (nullable = true)
 |-- wav_match_flag: string (nullable = true)

In [3]:
df.count()

19663930

In [6]:
zones_df = spark.read.option("header", True).csv(
    "hdfs://uber-hadoop-master:9000/data/reference/taxi_zone_geometries.csv"
)

zones_df.printSchema()

zones_df.limit(10).toPandas()

root
 |-- location_id: string (nullable = true)
 |-- borough: string (nullable = true)
 |-- zone_name: string (nullable = true)
 |-- service_zone: string (nullable = true)
 |-- polygon_wkt: string (nullable = true)

,location_id,borough,zone_name,service_zone,polygon_wkt
0,1,EWR,Newark Airport,EWR,POLYGON ((-74.18445299999996 40.69499600000009...
1,2,Queens,Jamaica Bay,Boro Zone,MULTIPOLYGON (((-73.82337597260663 40.63898704...
2,3,Bronx,Allerton/Pelham Gardens,Boro Zone,POLYGON ((-73.84792614099985 40.87134223400012...
3,4,Manhattan,Alphabet City,Yellow Zone,POLYGON ((-73.97177410965318 40.72582128133725...
4,5,Staten Island,Arden Heights,Boro Zone,POLYGON ((-74.17421738099989 40.56256808600009...
5,6,Staten Island,Arrochar/Fort Wadsworth,Boro Zone,POLYGON ((-74.06367318899999 40.60219816600014...
6,7,Queens,Astoria,Boro Zone,POLYGON ((-73.90413637799996 40.76752031700003...
7,8,Queens,Astoria Park,Boro Zone,POLYGON ((-73.92334041500001 40.77512891200012...
8,9,Queens,Auburndale,Boro Zone,POLYGON ((-73.78502434699996 40.76103651600005...
9,10,Queens,Baisley Park,Boro Zone,POLYGON ((-73.78326624999988 40.68999429300012...